name: Checkstyle and Tests

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Checkstyle and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Get java-version
        run: |
          BUILD_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: Compile
        run: mvn -X compile
      - name: Checkstyle
        run: mvn -X validate
      - name: Test
        run: mvn -X test
      - name: GitLint
        run: |
          pip install gitlint
          gitlint --config=gitlint/gitlint.cfg --commits "${{ github.event.pull_request.base.sha }}..HEAD" --fail-without-commits --verbose --debug
